auth 1.0
kjhk

Eval working

model

ProbTempStatique

Crud for problem

Creating problem of type "Number Gen" done

feat:Number gen template done.
some error in useEffect but it works.
Missing creating the user in/out.
missing checking the answer and effects.

fix: user model

Create README.md

Update README.md

draft: backend generating problem

newProfileSetup

editProfile

Add and Get a gen problem

Prepare GenProb's services for frontend

feat: Input generation done

Update README.md

Update README.md

Update README.md

Update README.md

feat: answer submission (missing DB sync)

Update README.md

Delete and Update api for GenProb

Update Profile

Update README.md

feat: answer submission
score counting
prevention from retrying

featProfileEditCancelSave &SuccessFailCreatingProb

fix: generating problem form

feat Navbar
Fix App.js new navbar component

feat Home page (get all problem on home page)

Update README.md

Update README.md

handle sign-in problem

Backend: API Get all users

Frontend: Data from DB for Standings page

fix: right answer on first try

Update README.md

readme

fix: standing has number of problems solved

feat: standing current user marked

feat: standing flags
error: standing not waiting for API

feat: Standings countries flags

feat: Standing country filter
to fix: countries unordered in standings and profile

fix Dashboard Admin

fix: ordered country names,
and cached for loading speed
loading icon on loading items

feat: Only admins see admins in standings

fix: admin Id made clear

fix: neji node modules

fix Coutry Stats

feat: profile image upload

fix: loading buttons

fix: default coutry in dropDown

fix: Home page styles (CSS)

feat: Qna style problems
fix: some refractoring

fix: problem creating: Dropdown -> buttons

fix: preformat username and Email

fix: Navbar

feat: standing sorting

fixHome Probs

fix some home colors

fixes: Front details

Create LICENSE

Create CODE_OF_CONDUCT.md

Create CODE_OF_CONDUCT.md

Update issue templates

Env fix
gitignore fix

Fixing dependency